### ISSUE TITLE
UW Accordion sections show duplicate file attachments

### ISSUE THREAD

**Issue by jbleys** [uweb/uw-2014#146] opened 2020-05-28 17:36 UTC
Hi,

I have a page that lists uploaded files (to that page) below the regular content. _See image 1_. For this example it shows one PDF under the Attachments heading. The user simply adds media to a page and the Attachment list is generated automatically. 

image 1:
![Accordion-issue_1](https://user-images.githubusercontent.com/2615272/83173358-eac62d80-a0e6-11ea-869a-5eede39e8fc4.JPG)

The page also has two accordion features. The first Accordion is from the [Shortcodes Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/) plugin, and the second is from the UW Boundless theme.

When I open an accordion item in the SU Accordion it displays the nested content, as expected. _See image 2_.

image 2:
![Accordion-issue_2](https://user-images.githubusercontent.com/2615272/83173409-fade0d00-a0e6-11ea-8435-b6ca7b3ef913.JPG)

But when I open the same accordion item created with the UW Accordion it shows another (duplicate) listing of the attached files. _See image 3_.

image 3:
![Accordion-issue_3](https://user-images.githubusercontent.com/2615272/83173456-092c2900-a0e7-11ea-8e1c-7bdcb13fca9f.JPG)

This behavior happens for each section of the UW Accordion. 

I can move ahead and use the SU Accordion for now, but I'd rather user the Boundless Accordion. 

Let me know if there are any questions.

Thanks,

Jasper Bleijs
Department of Global Health | University of Washington

**Comment by lcaple** [comment] 2020-05-28 21:36
Hi Jasper,

I can look into it and see if it's a programmatic problem, but without insight into your site setup and how you're getting the error, it'll be hard to track down the bug. If you could answer these questions I can investigate further:

- What version of WordPress and PHP are you using?
- Are you leveraging a plugin or modified template to show the page attachments, or is this from the editor?
- Are you using uw-2014 as is, a modified version, or a child theme?
- Can you give me to steps to reproduce this error (including the code in your page editor)?

Thanks!

**Comment by jbleys** [comment] 2020-05-28 22:49
Hi Lauren,

Thanks for your quick response.

- I'm using WordPress 5.4.1 and PHP 7.2.23. The site's running on the depts server.

- The file attachments are created with use of the [WP Attachments](https://wordpress.org/plugins/wp-attachments/) plugin. This plugin recognizes the distinction between attached files (i.e. Media added directly to a Page or Post), and unattached files (i.e. Media added to the Media library).
At first I though this plugin was the culprit, but after trying it with the SU Accordion which does not produce the issue, I believe the issue is with the UW Accordion.

- I'm using  a child-theme.

- Instead of giving you the code from the editor, I've given you Editor access to the site. So feel free to take a look at the page here: https://depts.washington.edu/deptgh/dev/intranet/coronavirus/
It's a test site, so no real harm can be done. There's a login link in the footer.

Thanks,
Jasper

**Comment by lcaple** [comment] 2020-05-28 23:09
This issue is specifically related to how the third party plugin WP Attachments works. It adds a filter to WordPress' **the_content**, which we also use for the shortcode output on our accordions. I am very hesitant to alter this since it has a lot of downstream implications on content and was likely done for a very specific reason.

I'm going to add this to our list of bugs to investigate further. For the time being if you would like to use WP Attachments alongside accordions on the page, you'll have to stick to Shortcodes Ultimate.

Alternatively, you could override accordion output in your childtheme to not use the the_content filters by modifying/extending the **UW_AccordionShortcode** class. It can be found in [class.accordion-shortcode.php](https://github.com/uweb/uw-2014/blob/master/setup/class.accordion-shortcode.php)

**Comment by jbleys** [comment] 2020-05-28 23:25
Hi Lauren,

I agree with your assessment about possible downstream implications and that you want to be cautious here. 

Thanks for keeping this on your radar though, and since this is not a work stoppage issue on my side I can absolutely switch to using the SU Accordions and simultaneously look into extending the UW Accordion class in the child-theme.

Your feedback and time is appreciated.

Kind regards,
Jasper

**Comment by jbleys** [comment] 2020-06-09 01:15
Hi Lauren,

I want to let you know that I'm moving away from the [WP Attachment](https://wordpress.org/plugins/wp-attachments/) plugin, and shifting to the [Attachments](https://wordpress.org/plugins/attachments/) plugin.

This plugin seems to better align with my needs, and does not appear to conflict with the UW Accordion shortcode.

Feel free to close the issue.

Thanks,
Jasper

**Comment by lcaple** [comment] 2020-06-09 03:32
Thanks for letting me know. The team will keep this on our radar but I will close this for now. Thanks!

**Closed by lcaple** 2020-06-09 03:32 UTC
Labels: Bug, Child Theme, Plugins
