### ISSUE TITLE
URL masking messes up the website look a little bit

### ISSUE THREAD

**Issue by DTaha** [uweb/uw-2014#72] opened 2017-06-30 20:50 UTC
We are using the theme on our website (http://depts.washington.edu/uwmxl/) whose URL has been masked (http://www.wxml.math.washington.edu/). The theme looks a bit weird on the masked URL on desktop (I checked on Google Chrome and Microsoft Edge). Both websites look fine on mobile phones.

Under Settings -> General, it has the correct URLs:
WordPress Address (URL) http://depts.washington.edu/uwmxl//wordpress
Site Address (URL) http://www.wxml.math.washington.edu
This does not solve the problem. :/

**Comment by lcaple** [comment] 2018-03-26 18:22
This issue is caused by where the Encode Sans font files are being served from, not the theme.

Many systems administrators restrict serving files from one domain (depts.washington.edu) to another domain (www.wxml.math.washington.edu) for security reasons. Masking the URL is still making the call from a domain that's not allowed.

You may want to ask the depts administrators if they're willing to add your URL to their exceptions list.

Closing.

**Closed by lcaple** 2018-03-26 18:22 UTC
Labels: question
