### ISSUE TITLE
Missing argument in call of text_cut() method in content-page-noheader.php

### ISSUE THREAD

**Issue by mattlam-uw** [uweb/uw-2014#103] opened 2018-06-21 22:48 UTC
Looking in our apache logs, I noticed a bunch of errors pointing to line 29 of /content-page-noheader.php.

The problem is that the text_cut() method defined further up in the file is expecting an argument for the 'text' parameter. The call to text_cut() in line 29 provides no value.

You could fix either of two ways: (1) remove 'text' from the list of parameters -- it looks like the function will overwrite whatever is passed anyway, or (2) provide a default value, such as 'null'.

I would have submitted a PR, but I apparently don't have permissions.

Thanks,
Matt

**Comment by lcaple** [comment] 2018-06-25 17:02
This is a duplicate of #98

**Comment by lcaple** [comment] 2018-07-02 21:56
Fixed in the latest commit.

**Closed by lcaple** 2018-07-02 21:56 UTC
Labels: Bug
